import type { WorldPortalDef } from "../types";

export const WORLD_PORTALS: WorldPortalDef[] = [
  {
    id: "portal_arcade",
    name: "Разлом Мини-игр",
    world: "hellfire",
    x: 12,
    y: 1188,
    width: 32,
    height: 32,
    color: "#a855f7",
  },
  {
    id: "portal_class_select",
    name: "Алтарь Перевоплощения",
    world: "hellfire",
    x: 565,
    y: 600,
    width: 32,
    height: 32,
    color: "#38bdf8",
  },
  {
    id: "portal_arinar",
    name: "Фрактал Бабочки: «Аринар»",
    world: "hellfire",
    targetWorld: "arinar",
    targetX: 300,
    targetY: 600,
    x: 240,
    y: 600,
    width: 36,
    height: 36,
    color: "#818cf8",
  },
  {
    id: "portal_hellfire",
    name: "Разлом: «Мир Адского Пламени»",
    world: "arinar",
    targetWorld: "hellfire",
    targetX: 300,
    targetY: 600,
    x: 240,
    y: 600,
    width: 36,
    height: 36,
    color: "#f97316",
  },
];